config/routes.rb
Blowseeds::Application.routes.draw do
  get "sessions/new"

  resources :users, :categories
  resources :sessions, :only => [:new, :create, :destroy]
  resources :products, :only => [:create, :destroy]

  match '/' => 'home#index'
  match '/signup',  :to =>  'users#new'
  match '/signin',  :to =>  'sessions#new'
  match '/signout', :to =>  'sessions#destroy'

    
    

    root :to  => "home#index"
   
  
  
end

app/models/category.rb
class Category < ActiveRecord::Base
   attr_accessible :name, :active
  
   validates :name, :presence => true,
                         :length => { :maximum => 80}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @categories = Category.find(:all, :order => "name asc")
    @title = "Category Listings"
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @category = Category.find(params[:id])
    @title = @category.name
    respond_to do |format|
      format.html # profile.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categorys/new
  # GET /categorys/new.xml
  def new
    @category = Category.new
    @title = "Registration"
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categorys/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @category = Category.new(params[:category])
    
    respond_to do |format|
      if @category.save
       
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
       
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categorys_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/categories/index.html.erb
<div id="main_content" class="container_12 clearfix">

 <div class="grid_4 box">
<h1>Category Listings</h1>

<table id="cat-table">
 

<% @categories.each do |category| %>
  <tr>
    <td><%= link_to category.name, category %></td>
    
    
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New category', new_category_path %>
</div>

 <hr class="grid_12"></hr>

</div>

app/views/categories/new.html.erb
<div id="main_content" class="container_12 clearfix">
  
   <div class="grid_4 box">
        <h2>New Category</h2>
        <article id="errors">
          <%= render 'shared/error_messages' 
          %>
        </article>
        <%= form_for(@category) do |f| %>
          <div class='field'>
            <%= f.label :name %><br/>
            <%= f.text_field :name %>
          </div>
                   
          <div class='actions'>
            <%= f.submit "Add Category" %>
          </div>
          
          <% end %>
          
  


<%= #link_to 'Back', category_path 
%>
</div>

 <hr class="grid_12"></hr>

</div>

app/views/categories/show.html.erb
<div id="main_content" class="container_12 clearfix">

 <div class="grid_4 box">
<h1>Category: <%= @category.name %></h1>
<p id="notice"><%= notice %></p>

<p>
  <b>Categories:</b>
  <%= @category.name %>
</p>



<%= #link_to 'Edit', edit_user_path(@user) 
  link_to 'All Categories', '/categories'
%> |
URL: <%= #link_to  users_path(@user), @user 
%>
</div>

 <hr class="grid_12"></hr>
</div>